---
image: node:latest

variables:
  NODE_VERSION: "12.11.1"

stages:
  - test
  - build

# ----------------------------------
# TEST
# ----------------------------------

test client:
  stage: test
  image: node:$NODE_VERSION
  before_script:
    - cd client
  script:
    - npm install
    - npm run test-client-ci

# ----------------------------------
# BUILD
# ----------------------------------

build client:
  only:
    - master
  stage: build
  image: node:$NODE_VERSION
  before_script:
    - cd client
  script:
    - npm install
  #  - npm run start-server

build server:
  only:
    - master
  stage: build
  image: node:$NODE_VERSION
  before_script:
    - cd server
  script:
    - npm install
#    - npm run build
